AWSTemplateFormatVersion: "2010-09-09"
Description: "Codebuild Web App"

Parameters:
  RepoUrl:
    Type: String
    Description: "Github Repository Location"
    Default: "https://github.com/phamtrongngh/aws-labs-for-kids"

  RepoAppDir:
    Type: String
    Description: "Github Repository App Directory"
    Default: "labs/codebuild-web-app/web-app"

Resources:
  EcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "codebuild-web-app"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: "MUTABLE"
      EmptyOnDelete: true

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Action": [
                    "cloudformation:*",
                    "ecr:*",
                    "s3:*",
                    "logs:*",
                    "codebuild:*"
                  ],
                  "Resource": "*"
                }
              ]
            }

    # This resource allows CodeBuild to connect with Github using Personal Access Token.
  CodeBuildSourceCredential:
      Type: AWS::CodeBuild::SourceCredential
      Properties:
        AuthType: PERSONAL_ACCESS_TOKEN
        ServerType: GITHUB
        Token: "{{resolve:ssm:/codebuild/github-token}}"

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "codebuild-web-app"
      Description: "CodeBuuld Project for Web App"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: "NO_ARTIFACTS"

      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"

      Source:
        Type: "GITHUB"
        Location: !Ref RepoUrl
        BuildSpec: !Sub ${RepoAppDir}/buildspec.yml
        ReportBuildStatus: true

      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH,PULL_REQUEST_MERGED
            - Type: HEAD_REF
              Pattern: ^refs/heads/master$
              ExcludeMatchedPattern: false
            - Type: FILE_PATH
              Pattern: !Sub ${RepoAppDir}/*

      TimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
          GroupName: "CodeBuildLogs"
          StreamName: "CodeBuildStream"

      ConcurrentBuildLimit: 1

    DependsOn: CodeBuildSourceCredential
