AWSTemplateFormatVersion: "2010-09-09"
Description: "Codebuild Web App"

Resources:
  EcrRepository:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "codebuild-web-app"
      ImageScanningConfiguration:
        ScanOnPush: true
      ImageTagMutability: "MUTABLE"
      EmptyOnDelete: true

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "CloudWatchLogsPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "CodeBuildPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "codebuild:CreateReportGroup"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "S3GetObjectPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "s3:GetObject",
                    "s3:GetObjectVersion"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "S3PutObjectPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "s3:PutObject"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "S3BucketIdentity",
                  "Effect": "Allow",
                  "Action": [
                    "s3:GetBucketAcl",
                    "s3:GetBucketLocation"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "CreateReportPolicy",
                  "Effect": "Allow",
                  "Action": "codebuild:CreateReport",
                  "Resource": "*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                      "codebuild:BatchPutTestCases",
                      "codebuild:UpdateReport"
                  ],
                  "Resource": "*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                    "ecr:GetAuthorizationToken",
                    "ecr:BatchCheckLayerAvailability",
                    "ecr:GetDownloadUrlForLayer",
                    "ecr:BatchGetImage",
                    "ecr:BatchDeleteImage",
                    "ecr:CompleteLayerUpload",
                    "ecr:DescribeImages",
                    "ecr:DescribeRepositories",
                    "ecr:UploadLayerPart",
                    "ecr:InitiateLayerUpload",
                    "ecr:PutImage"
                  ],
                  "Resource": "*"
                }
              ]
            }

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "codebuild-web-app"
      Description: "CodeBuuld Project for Web App"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: "NO_ARTIFACTS"
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
      Source:
        Type: "GITHUB"
        Location: "https://github.com/phamtrongngh/aws-labs-for-kids.git"
        BuildSpec: "labs/codebuild-web-app/web-app/buildspec.yml"
        ReportBuildStatus: true

      TimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
          GroupName: "CodeBuildLogs"
          StreamName: "CodeBuildStream"

      ConcurrentBuildLimit: 1
