AWSTemplateFormatVersion: "2010-09-09"
Description: "Codebuild Introduction"

Resources:
  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument: |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "CloudWatchLogsPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "CodeBuildPolicy",
                  "Effect": "Allow",
                  "Action": [
                    "codebuild:CreateReportGroup"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "CreateReportPolicy",
                  "Effect": "Allow",
                  "Action": "codebuild:CreateReport",
                  "Resource": "*"
                },
                {
                  "Effect": "Allow",
                  "Action": [
                      "codebuild:BatchPutTestCases",
                      "codebuild:UpdateReport"
                  ],
                  "Resource": "*"
                }
              ]
            }

  CodeBuildProject:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Name: "codebuild-intro"
      Description: "CodeBuuld Project for Introduction"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: "NO_ARTIFACTS"
      Environment:
        Type: "LINUX_CONTAINER"
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:5.0"
      Source:
        Type: "NO_SOURCE"
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - echo "Hello, World! This is a CodeBuild Project for Introduction"
                
      TimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          Status: "ENABLED"
          GroupName: "CodeBuildLogs"
          StreamName: "CodeBuildStream"

      ConcurrentBuildLimit: 1
